package ChuongTrinh;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class DangNhap extends javax.swing.JFrame {

    Connection ketNoi;
    ArrayList<NguoiDung> listND = new ArrayList<NguoiDung>();
    String username;
    String pass;
    String chucvu;
    static String Username, ChucVu;
    NguoiDung nd;

    public DangNhap() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public void ketNoiCSDL() throws SQLException {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost;databaseName=QuanLyQuanCaPhe";
            String user = "sa";
            String pass = "123";
            ketNoi = DriverManager.getConnection(url, user, pass);

        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL");
        }

    }

    public void loadDuLieuNguoiDung() throws SQLException {
        ketNoiCSDL();
        String sql = "select * from NguoiDung";
        PreparedStatement cauLenh = ketNoi.prepareStatement(sql);
        ResultSet ketQua = cauLenh.executeQuery();
        while (ketQua.next()) {
            username = ketQua.getString(1);
            pass = ketQua.getString(2);
            chucvu = ketQua.getString(3);
            nd = new NguoiDung(username, pass, chucvu);
            listND.add(nd);

        }

    }

    public void checkUserNamePassWord() {
        int dem = 0;
        for (int i = 0; i < listND.size(); i++) {
            username = listND.get(i).username;
            pass = listND.get(i).password;
            if (txtUsername.getText().trim().equals(username) && pswPassword.getText().equals(pass)) {

                new LoadingForm().setVisible(true);
                this.dispose();
            } else if (username.equals(txtUsername.getText()) && !pass.equals(pswPassword.getText())) {
                lblCheckUsername.setText("");
                lblCheckPassWord.setForeground(new Color(255, 255, 135));
                lblCheckPassWord.setText("Mật khẩu sai");
                dem = 0;
                break;
            }
            if (!username.equals(txtUsername.getText())) {
                dem++;
            }

        }
        if (dem > 0) {
            lblCheckUsername.setForeground(new Color(255, 255, 135));
            lblCheckUsername.setText("Username không tồn tại");
        }
    }

    public boolean checkBoTrong() {
        int loi = 0;
        if (txtUsername.getText().equals("Username") || txtUsername.getText().isEmpty()) {
            lblCheckUsername.setForeground(new Color(255, 255, 135));
            lblCheckUsername.setText("Vui lòng nhập username");
            loi++;
        } else {
            lblCheckUsername.setText("");
        }

        if (pswPassword.getText().equals("Password") || pswPassword.getText().isEmpty()) {
            lblCheckPassWord.setForeground(new Color(255, 255, 135));
            lblCheckPassWord.setText("Bạn chưa nhập password");
            loi++;
        } else {
            lblCheckPassWord.setText("");
        }
        if (loi > 0) {
            return false;
        }
        return true;

    }

    public void phanQuyen() {
        for (int i = 0; i < listND.size(); i++) {

            if (txtUsername.getText().equals(listND.get(i).username)) {
                ChucVu = listND.get(i).chucVu;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCoffee = new javax.swing.JLabel();
        lblNen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblCheckUsername = new javax.swing.JLabel();
        lblCheckPassWord = new javax.swing.JLabel();
        lblHienMatKhau = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        pswPassword = new javax.swing.JPasswordField();
        lblUserName = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblQuenMatKhau = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCoffee.setForeground(new java.awt.Color(255, 255, 255));
        lblCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cafe_500px.png"))); // NOI18N
        jPanel1.add(lblCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 309, 330));

        lblNen.setBackground(new java.awt.Color(153, 153, 255));
        lblNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nen1.png"))); // NOI18N
        lblNen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        lblNen.setOpaque(true);
        jPanel1.add(lblNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        jPanel3.setBackground(new java.awt.Color(38, 97, 215));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_login.png"))); // NOI18N
        lblLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLoginMouseMoved(evt);
            }
        });
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
        });
        jPanel3.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        lblCheckUsername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel3.add(lblCheckUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 290, 20));

        lblCheckPassWord.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel3.add(lblCheckPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 290, 20));

        lblHienMatKhau.setForeground(new java.awt.Color(38, 97, 215));
        lblHienMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        lblHienMatKhau.setText("Hien");
        lblHienMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHienMatKhauMouseClicked(evt);
            }
        });
        jPanel3.add(lblHienMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 30, 30));

        txtUsername.setBackground(new java.awt.Color(38, 97, 215));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("Username");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        jPanel3.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 290, 40));

        pswPassword.setBackground(new java.awt.Color(38, 97, 215));
        pswPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        pswPassword.setForeground(new java.awt.Color(255, 255, 255));
        pswPassword.setText("Password");
        pswPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pswPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswPasswordFocusLost(evt);
            }
        });
        jPanel3.add(pswPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 290, 40));

        lblUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_24px.png"))); // NOI18N
        jPanel3.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblPass.setBackground(new java.awt.Color(255, 255, 255));
        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_padlock_24px.png"))); // NOI18N
        jPanel3.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        lblQuenMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setText("Forget Password ?");
        lblQuenMatKhau.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseMoved(evt);
            }
        });
        lblQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseExited(evt);
            }
        });
        jPanel3.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 60, 440, -1));

        lblExit.setBackground(new java.awt.Color(38, 97, 215));
        lblExit.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblExit.setForeground(new java.awt.Color(226, 226, 226));
        lblExit.setText("  X");
        lblExit.setOpaque(true);
        lblExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblExitMouseMoved(evt);
            }
        });
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel3.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 50, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblQuenMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseExited
        // TODO add your handling code here:
        lblQuenMatKhau.setText("Forget Password ?");
        lblQuenMatKhau.setForeground(Color.white);
    }//GEN-LAST:event_lblQuenMatKhauMouseExited

    private void lblQuenMatKhauMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseMoved
        // TODO add your handling code here:
        lblQuenMatKhau.setText("<html><u>Forget Password ?</u></html>");
        lblQuenMatKhau.setForeground(new Color(85, 255, 165));
    }//GEN-LAST:event_lblQuenMatKhauMouseMoved

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
        if (txtUsername.getText().isEmpty()) {
            txtUsername.setText("Username");

        }

    }//GEN-LAST:event_txtUsernameFocusLost

    private void pswPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswPasswordFocusLost
        // TODO add your handling code here:
        if (pswPassword.getText().isEmpty()) {
            pswPassword.setText("Password");
        }

    }//GEN-LAST:event_pswPasswordFocusLost

    private void lblExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseMoved
        // TODO add your handling code here:
        lblExit.setForeground(Color.white);
        lblExit.setBackground(Color.red);
    }//GEN-LAST:event_lblExitMouseMoved

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setForeground(new Color(226, 226, 226));
        lblExit.setBackground(new Color(38, 97, 215));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblHienMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHienMatKhauMouseClicked
        if (lblHienMatKhau.getText().equals("Hien")) {
            pswPassword.setEchoChar((char) 0);
            lblHienMatKhau.setText("An");
            lblHienMatKhau.setIcon(new ImageIcon(getClass().getResource("/images/hidePass.png")));

        } else if (lblHienMatKhau.getText().equals("An")) {
            pswPassword.setEchoChar('*');
            lblHienMatKhau.setIcon(new ImageIcon(getClass().getResource("/images/eye.png")));
            lblHienMatKhau.setText("Hien");
        }
    }//GEN-LAST:event_lblHienMatKhauMouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        try {
            if (checkBoTrong()) {

                loadDuLieuNguoiDung();
                checkUserNamePassWord();
                Username = txtUsername.getText().trim();
                phanQuyen();

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi load cơ sở dữ liệu");
        }
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseMoved
        lblLogin.setIcon(new ImageIcon(getClass().getResource("/images/button_login_hover.png")));
    }//GEN-LAST:event_lblLoginMouseMoved

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        lblLogin.setIcon(new ImageIcon(getClass().getResource("/images/button_login.png")));
    }//GEN-LAST:event_lblLoginMouseExited

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if (txtUsername.getText().equals("Username")) {
            txtUsername.setText("");
            txtUsername.requestFocus();

        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void pswPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswPasswordFocusGained
        if (pswPassword.getText().equals("Password")) {
            pswPassword.setText("");

        }
    }//GEN-LAST:event_pswPasswordFocusGained

    private void lblQuenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseClicked
        try {
            new QuenMatKhau().setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi!!");
        }
        this.dispose();
    }//GEN-LAST:event_lblQuenMatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCheckPassWord;
    private javax.swing.JLabel lblCheckUsername;
    private javax.swing.JLabel lblCoffee;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHienMatKhau;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNen;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
